---
# tasks file for nordvpn
- name: Ensure openvpn is installed
  ansible.builtin.package:
    name:
      - openvpn
    state: present

- name: Ensure NordVPN auth file is present on remote
  ansible.builtin.copy:
    dest: /etc/openvpn/pass
    content: "{{ role_nordvpn_username }}\n{{ role_nordvpn_password }}\n"
    mode: "0600"
    owner: root
    group: root
  notify: Restart openvpn

- name: Ensure NordVPN connection file is present on remote
  ansible.builtin.get_url:
    url: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/{{ nordvpn_server }}.ovpn
    dest: /etc/openvpn/client.conf
    mode: "0644"
    owner: root
    group: root
  notify: Restart openvpn

- name: Ensure openvpn config is present on remote
  ansible.builtin.copy:
    src: openvpn
    dest: /etc/default/openvpn
    mode: "0644"
    owner: root
    group: root
  notify: Restart openvpn

- name: Ensure openvpn service is enabled and started
  ansible.builtin.service:
    name: openvpn@client
    state: started
    enabled: true
