---
# tasks file for nordvpn
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Ensure openvpn is installed
  ansible.builtin.package:
    name:
      - openvpn
    state: present

- name: Ensure NordVPN auth file is present on remote
  ansible.builtin.copy:
    dest: /etc/openvpn/pass
    content: "{{ nordvpn_username }}\n{{ nordvpn_password }}\n"
    mode: "0600"
    owner: root
    group: root
  notify: Restart openvpn

- name: Ensure NordVPN connection file is present on remote
  ansible.builtin.get_url:
    url: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/{{ nordvpn_server }}.ovpn
    dest: /root/client.conf
    mode: "0644"
    owner: root
    group: root
  register: nordvpn_connection_file

- name: Ensure NordVPN connection file is present on remote
  ansible.builtin.copy:
    src: /root/client.conf
    dest: /etc/openvpn/client.conf
    remote_src: true
    force: "{{ nordvpn_connection_file.changed }}"
    mode: "0644"
    owner: root
    group: root
  notify: Restart openvpn

- name: Get additional address ips
  ansible.builtin.uri:
    url: "{{ item }}"
    return_content: true
  register: additional_address_ips
  with_items: "{{ nordvpn_additional_route_addresses }}"

- name: Set additional routes
  ansible.builtin.blockinfile:
    path: /etc/openvpn/client.conf
    insertafter: ^verify-x509-name.*\n
    block: |
      
      {% for route in additional_address_ips.results %}
      {% for route_ip in route.json.records.A %}
      route {{ route_ip.address }} 255.255.255.255 vpn_gateway
      {% endfor %}
      {% endfor %}
      {% for ip in nordvpn_additional_route_ips %}
      route {{ ip }} 255.255.255.255 vpn_gateway
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK additional routes"

- name: Set no_redirect_gateway
  ansible.builtin.lineinfile:
    path: /etc/openvpn/client.conf
    line: pull-filter ignore redirect-gateway
    regexp: ^pull-filter ignore redirect-gateway
    insertafter: ^verify-x509-name.*\n
    state: "{{ nordvpn_ignore_redirect_gateway and 'present' or 'absent' }}"
  notify: Restart openvpn

- name: Set nordvpn_route_nopull
  ansible.builtin.lineinfile:
    path: /etc/openvpn/client.conf
    line: route-nopull
    regexp: ^route-nopull
    insertafter: ^verify-x509-name.*\n
    state: "{{ nordvpn_route_nopull and 'present' or 'absent' }}"
  notify: Restart openvpn

- name: Ensure openvpn config is present on remote
  ansible.builtin.copy:
    src: openvpn
    dest: /etc/default/openvpn
    mode: "0644"
    owner: root
    group: root
  notify: Restart openvpn

- name: Ensure openvpn service is enabled and started
  ansible.builtin.service:
    name: openvpn@client
    state: started
    enabled: true
  when: not nordvpn_is_test or nordvpn_is_test is undefined
