---
# tasks file for nordvpn
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == 'Debian'

- name: Ensure OpenVPN is installed
  ansible.builtin.package:
    name: openvpn
    state: present

- name: Ensure NordVPN auth file is present on remote
  ansible.builtin.copy:
    dest: /etc/openvpn/pass
    content: "{{ nordvpn_username }}\n{{ nordvpn_password }}\n"
    mode: "0600"
    owner: root
    group: root
  notify: Restart openvpn

- name: Download NordVPN connection file
  ansible.builtin.get_url:
    url: https://downloads.nordcdn.com/configs/files/ovpn_legacy/servers/{{ nordvpn_server }}.ovpn
    dest: /etc/openvpn/client.conf
    mode: "0644"
    owner: root
    group: root
  register: nordvpn_connection_file
  failed_when: nordvpn_connection_file.status != 200
  notify: Restart openvpn

- name: Get additional address IPs
  ansible.builtin.uri:
    url: "{{ item }}"
    return_content: true
  register: additional_address_ips
  loop: "{{ nordvpn_additional_route_addresses }}"

- name: Set additional routes in client.conf
  ansible.builtin.blockinfile:
    path: /etc/openvpn/client.conf
    insertafter: ^verify-x509-name.*\n
    block: |
      {% for route in additional_address_ips.results %}
      {% for route_ip in route.json.records.A %}
      route {{ route_ip.address }} 255.255.255.255 vpn_gateway
      {% endfor %}
      {% endfor %}
      {% for ip in nordvpn_additional_route_ips %}
      route {{ ip }} 255.255.255.255 vpn_gateway
      {% endfor %}
    marker: "# {mark} ANSIBLE MANAGED BLOCK additional routes"
  notify: Restart openvpn

- name: Set OpenVPN password file in client.conf
  ansible.builtin.lineinfile:
    path: /etc/openvpn/client.conf
    line: auth-user-pass pass
    regexp: ^auth-user-pass
    state: present
  notify: Restart openvpn

- name: Set no_redirect_gateway in client.conf
  ansible.builtin.lineinfile:
    path: /etc/openvpn/client.conf
    line: pull-filter ignore redirect-gateway
    regexp: ^pull-filter ignore redirect-gateway
    insertafter: ^verify-x509-name.*\n
    state: "{{ nordvpn_ignore_redirect_gateway and 'present' or 'absent' }}"
  notify: Restart openvpn

- name: Set nordvpn_route_nopull in client.conf
  ansible.builtin.lineinfile:
    path: /etc/openvpn/client.conf
    line: route-nopull
    regexp: ^route-nopull
    insertafter: ^verify-x509-name.*\n
    state: "{{ nordvpn_route_nopull and 'present' or 'absent' }}"
  notify: Restart openvpn

- name: Ensure OpenVPN config is present on remote
  ansible.builtin.copy:
    src: openvpn
    dest: /etc/default/openvpn
    mode: "0644"
    owner: root
    group: root
  notify: Restart openvpn

- name: Ensure OpenVPN service is enabled and started
  ansible.builtin.systemd:
    name: openvpn@client
    state: started
    enabled: true
  when: nordvpn_is_test is undefined or not nordvpn_is_test
