---
# handlers file for nordvpn
- name: Restart openvpn
  ansible.builtin.systemd:
    name: openvpn@client
    state: restarted
    enabled: true
    daemon_reload: true
  when: not nordvpn_is_test or nordvpn_is_test is undefined
