---
# handlers file for nordvpn
- name: Restart openvpn
  ansible.builtin.service:
    name: openvpn@client
    state: restarted
    enabled: true
  when: nordvpn_is_test == false or nordvpn_is_test is undefined
